# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
