# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20161010_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetype',
            name='url_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
