# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_gradetype_language_exam_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetype',
            name='url_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
